server:
  port: 8085

spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8080/eureka/
      #集群模式
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/,http://127.0.0.1:8083/eureka/
