server:
  port: 8080

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 5000 # 扫描失效服务的间隔时间（缺省为60*1000ms）
    enable-self-preservation: false # 关闭自我保护模式（默认为打开）


