server:
  port: 8083

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 5000 # 扫描失效服务的间隔时间（缺省为60*1000ms）
    enable-self-preservation: false # 关闭自我保护模式（默认为打开）
